### ISSUE TITLE
browser.xul UNDEFINED_VAR

### ISSUE THREAD

**Issue by stevenschlansker** [MoonchildProductions/Tycho#50]
Seeing the following error on my Mac:
> mozbuild.preprocessor.Error: ('/Users/pale/jenkins/workspace/tycho/default/browser/base/content/browser.xul', 44, 'UNDEFINED_VAR', 'PRE_RELEASE_SUFFIX')

```
 4:34.85 /Users/pale/jenkins/workspace/tycho/default/netwerk/base/security-prefs.js: WARNING: no preprocessor directives found

 4:41.02   adding: install.rdf (deflated 52%)
 4:41.05   adding: plugins/Test.plugin/Contents/Info.plist (deflated 54%)
 4:41.05   adding: plugins/Test.plugin/Contents/MacOS/libnptest.dylib (deflated 66%)
 4:41.05   adding: plugins/SecondTest.plugin/Contents/Info.plist (deflated 59%)
 4:41.06   adding: plugins/SecondTest.plugin/Contents/MacOS/libnpsecondtest.dylib (deflated 66%)

 4:46.43 /Users/pale/jenkins/workspace/tycho/default/config/rules.mk:1518: warning: overriding commands for target `../../../dist/bin/modules/LoginManagerParent.jsm'
 4:46.43 /Users/pale/jenkins/workspace/tycho/default/config/rules.mk:1453: warning: ignoring old commands for target `../../../dist/bin/modules/LoginManagerParent.jsm'

 5:05.59 /Users/pale/jenkins/workspace/tycho/default/browser/base/content/browser-title.css: WARNING: no preprocessor directives found
 5:05.86 Traceback (most recent call last):
 5:05.87   File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
 5:05.87     "__main__", fname, loader, pkg_name)
 5:05.87   File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
 5:05.87     exec code in run_globals
 5:05.87   File "/Users/pale/jenkins/workspace/tycho/default/python/mozbuild/mozbuild/action/jar_maker.py", line 15, in <module>
 5:05.88     sys.exit(main(sys.argv[1:]))
 5:05.88   File "/Users/pale/jenkins/workspace/tycho/default/python/mozbuild/mozbuild/action/jar_maker.py", line 11, in main
 5:05.88     return mozbuild.jar.main(args)
 5:05.88   File "/Users/pale/jenkins/workspace/tycho/default/python/mozbuild/mozbuild/jar.py", line 531, in main
 5:05.88     jm.makeJar(infile, options.j)
 5:05.88   File "/Users/pale/jenkins/workspace/tycho/default/python/mozbuild/mozbuild/jar.py", line 254, in makeJar
 5:05.88     jardir)
 5:05.88   File "/Users/pale/jenkins/workspace/tycho/default/python/mozbuild/mozbuild/jar.py", line 352, in processJarSection
 5:05.88     self._processEntryLine(m, outHelper, jf)
 5:05.88   File "/Users/pale/jenkins/workspace/tycho/default/python/mozbuild/mozbuild/jar.py", line 394, in _processEntryLine
 5:05.88     pp.do_include(inf)
 5:05.88   File "/Users/pale/jenkins/workspace/tycho/default/python/mozbuild/mozbuild/preprocessor.py", line 788, in do_include
 5:05.88     self.handleLine(l)
 5:05.89   File "/Users/pale/jenkins/workspace/tycho/default/python/mozbuild/mozbuild/preprocessor.py", line 566, in handleLine
 5:05.89     self.write(aLine)
 5:05.89   File "/Users/pale/jenkins/workspace/tycho/default/python/mozbuild/mozbuild/preprocessor.py", line 430, in write
 5:05.89     filteredLine = self.applyFilters(aLine)
 5:05.89   File "/Users/pale/jenkins/workspace/tycho/default/python/mozbuild/mozbuild/preprocessor.py", line 412, in applyFilters
 5:05.89     aLine = f[1](aLine)
 5:05.89   File "/Users/pale/jenkins/workspace/tycho/default/python/mozbuild/mozbuild/preprocessor.py", line 745, in filter_substitution
 5:05.89     return self.varsubst.sub(repl, aLine)
 5:05.89   File "/Users/pale/jenkins/workspace/tycho/default/python/mozbuild/mozbuild/preprocessor.py", line 743, in repl
 5:05.90     raise Preprocessor.Error(self, 'UNDEFINED_VAR', varname)
 5:05.90 mozbuild.preprocessor.Error: ('/Users/pale/jenkins/workspace/tycho/default/browser/base/content/browser.xul', 44, 'UNDEFINED_VAR', 'PRE_RELEASE_SUFFIX')
 5:05.91 make[5]: *** [libs] Error 1
 5:05.91 make[4]: *** [browser/base/libs] Error 2
 5:05.91 make[3]: *** [libs] Error 2
 5:05.92 make[2]: *** [default] Error 2
 5:05.92 make[1]: *** [realbuild] Error 2
 5:05.92 make: *** [build] Error 2
```

**Comment by wolfbeast** [comment]
Pre-release suffix strings are no longer used. Easy fix.
